# Generated by Django 5.2.4 on 2025-07-08 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='management.unit')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='property_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='management.property')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مستند عقار',
                'verbose_name_plural': 'مستندات العقار',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255, verbose_name='اسم المستأجر')),
                ('tenant_id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء العقد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الإيجار')),
                ('payment_method', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract', to='management.unit')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
            },
        ),
        migrations.DeleteModel(
            name='RentalInfo',
        ),
    ]
