services:
  - type: web
    name: realestate-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: False
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_key
      - key: CLOUDINARY_API_SECRET
        value: your_secret
