# Generated by Django 5.2.4 on 2025-07-06 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان العقار')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='صورة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('archived', 'مؤرشف')], default='active', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإضافة بواسطة')),
            ],
        ),
    ]
