# Generated by Django 5.1.7 on 2025-03-22 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='requestimage',
            name='request',
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='owner_type',
            field=models.CharField(choices=[('owner', 'مالك مباشر'), ('agent', 'وسيط عقاري')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('floor', 'دور'), ('land', 'أرض'), ('building', 'عمارة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('buy', 'شراء'), ('rent', 'إيجار'), ('sell', 'بيع')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='RequestImage',
        ),
    ]
