# Generated by Django 5.2.4 on 2025-07-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_info',
            field=models.CharField(default='لا يوجد', max_length=255, verbose_name='وسيلة التواصل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم ترخيص الإعلان'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'بيع'), ('rent', 'إيجار')], default='لا يوجد', max_length=10, verbose_name='نوع العرض'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255, verbose_name='الوصف النصي للموقع'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('archived', 'مؤرشف')], default='active', editable=False, max_length=10, verbose_name='الحالة'),
        ),
    ]
