# Generated by Django 5.2.4 on 2025-07-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_contact_info_property_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المساحة بالمتر²'),
        ),
    ]
