# Generated by Django 5.1.7 on 2025-03-22 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_propertyimage_property_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='owner_type',
            field=models.CharField(choices=[('owner', 'مالك'), ('broker', 'وسيط')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('building', 'عمارة'), ('land', 'أرض')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('buy', 'شراء'), ('rent', 'استئجار')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('buy', 'شراء'), ('rent', 'إيجار'), ('sell', 'بيع')], max_length=10)),
                ('owner_type', models.CharField(choices=[('owner', 'مالك مباشر'), ('agent', 'وسيط عقاري')], max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('floor', 'دور'), ('land', 'أرض'), ('building', 'عمارة')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('details', models.TextField(blank=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
