# Generated by Django 5.1.7 on 2025-03-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyrequest_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='request_type',
            field=models.CharField(choices=[('sell', 'بيع'), ('rent', 'إيجار')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('buy', 'شراء'), ('rent', 'استئجار'), ('sell', 'بيع')], max_length=10),
        ),
    ]
