# Generated by Django 5.1.7 on 2025-03-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='details',
            field=models.TextField(),
        ),
    ]
