# Generated by Django 5.2.4 on 2025-07-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_options_remove_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تم الاعتماد من الإدارة'),
        ),
    ]
