# Generated by Django 5.2.4 on 2025-07-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='المدينة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(default=1, max_length=100, verbose_name='الحي'),
            preserve_default=False,
        ),
    ]
