# Generated by Django 5.1.7 on 2025-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyrequest_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_finance_available',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
