# Generated by Django 5.2.4 on 2025-07-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_city_property_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('archived', 'مؤرشف'), ('pending', 'قيد المراجعة')], default='active', editable=False, max_length=10, verbose_name='الحالة'),
        ),
    ]
