# Generated by Django 5.1.7 on 2025-03-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل؟'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الخبر'),
        ),
    ]
