# Generated by Django 5.1.7 on 2025-03-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_news_created_at_alter_news_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العقار'),
        ),
    ]
