# Generated by Django 5.1.7 on 2025-03-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='نبذة عنا')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب')),
                ('twitter', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('snapchat', models.URLField(blank=True, verbose_name='رابط سناب شات')),
            ],
            options={
                'verbose_name': 'إعدادات الفوتر',
                'verbose_name_plural': 'إعدادات الفوتر',
            },
        ),
    ]
