# Generated by Django 5.2.4 on 2025-07-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('reviewed', 'تم المراجعة'), ('contacted', 'تم التواصل')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
