# Generated by Django 5.2.4 on 2025-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_realestaterequest_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestaterequest',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المساحة بالمتر'),
        ),
        migrations.AddField(
            model_name='realestaterequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر المتوقع'),
        ),
        migrations.AddField(
            model_name='realestaterequest',
            name='city',
            field=models.CharField(default='الرياض', max_length=100, verbose_name='المدينة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestaterequest',
            name='district',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الحي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestaterequest',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('building', 'عمارة'), ('rest_house', 'استراحة'), ('other', 'أخرى')], default=1, max_length=20, verbose_name='نوع العقار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestaterequest',
            name='purpose',
            field=models.CharField(choices=[('sell', 'بيع'), ('buy', 'شراء'), ('rent_out', 'تأجير'), ('rent', 'استئجار')], default='الرياض', max_length=20, verbose_name='نوع الطلب'),
            preserve_default=False,
        ),
    ]
