# Generated by Django 5.2.4 on 2025-07-06 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_realestaterequest_area_realestaterequest_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realestaterequest',
            name='reserved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_requests', to=settings.AUTH_USER_MODEL, verbose_name='الوسيط الحاجز'),
        ),
    ]
