# Generated by Django 5.2.4 on 2025-07-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestaterequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة؟'),
        ),
    ]
