# Generated by Django 5.2.4 on 2025-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_realestaterequest_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestaterequest',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحجز'),
        ),
    ]
