# Generated by Django 5.2.4 on 2025-07-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_realestaterequest_reserved_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
